// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBl2bYZVx5xwvXsaRt4DEJiH39sSFwuf4',
    appId: '1:1052366263853:web:7b904ef6e48988fbcb4aa4',
    messagingSenderId: '1052366263853',
    projectId: 'finalproject-74364',
    authDomain: 'finalproject-74364.firebaseapp.com',
    storageBucket: 'finalproject-74364.firebasestorage.app',
    measurementId: 'G-K9J6GZXP16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk-IwRjY8s6d-GWpQjwxDTwK_oPXmcMdo',
    appId: '1:1052366263853:android:85d3fbb2cfebd833cb4aa4',
    messagingSenderId: '1052366263853',
    projectId: 'finalproject-74364',
    storageBucket: 'finalproject-74364.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASP0VKXzsQML-ndqsY-2K5F7JhcTycjBM',
    appId: '1:1052366263853:ios:a5e62360f529c37bcb4aa4',
    messagingSenderId: '1052366263853',
    projectId: 'finalproject-74364',
    storageBucket: 'finalproject-74364.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASP0VKXzsQML-ndqsY-2K5F7JhcTycjBM',
    appId: '1:1052366263853:ios:a5e62360f529c37bcb4aa4',
    messagingSenderId: '1052366263853',
    projectId: 'finalproject-74364',
    storageBucket: 'finalproject-74364.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBl2bYZVx5xwvXsaRt4DEJiH39sSFwuf4',
    appId: '1:1052366263853:web:7aae71087c163d79cb4aa4',
    messagingSenderId: '1052366263853',
    projectId: 'finalproject-74364',
    authDomain: 'finalproject-74364.firebaseapp.com',
    storageBucket: 'finalproject-74364.firebasestorage.app',
    measurementId: 'G-2KB7XEYRYK',
  );
}
